export const UPDATE_INPUT_VALUE = 'UPDATE_INPUT_VALUE';
export const HANDLE_FILTER_VISIBILITY = 'HANDLE_FILTER_VISIBILITY';
export const HANDLE_CARDS_VISIBILITY = 'HANDLE_CARDS_VISIBILITY';
export const HANDLE_STATUS_API = 'HANDLE_STATUS_API';
export const HANDLE_LOGIN_MODAL_VISIBILITY = 'HANDLE_LOGIN_MODAL_VISIBILITY';
export const HANDLE_SIGNUP_MODAL_VISIBILITY = 'HANDLE_SIGNUP_MODAL_VISIBILITY';

export const HANDLE_RESET_WHOLE_FILTER = 'RESET_WHOLE_FILTER';
export const HANDLE_SELECT_OPTION = 'SELECT_OPTION';
export const HANDLE_SELECT_YEAR = 'SELECT_YEAR';
export const HANDLE_PAGINATION = 'HANDLE_PAGINATION';
export const HANDLE_MOVIE_SEARCH = 'HANDLE_MOVIE_SEARCH';
export const HANDLE_RESEARCH_INPUT = 'HANDLE_RESEARCH_INPUT';
export const HANDLE_MOVIE_FAVORITE = 'HANDLE_MOVIE_FAVORITE';

export const FETCH_FAVORITE_LIST = 'FETCH_FAVORITE_LIST';
export const HANDLE_DATA_CARDS = 'HANDLE_DATA_CARDS';
export const TOGGLE_FAVORITE_MOVIE = 'TOGGLE_FAVORITE_MOVIE';
export const HANDLE_DETAILS_DATA = 'HANDLE_DETAILS_DATA';
export const HANDLE_CHECK_TOGGLING = 'HANDLE_CHECK_TOGGLING';
export const HANDLE_GET_INITIAL_GENRES = 'HANDLE_GET_INITIAL_GENRES';
